### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by Pryx** [server-status-project/server-status#26]
It should be possible to register for status updates sent via email, so users don't have to always check the status page. Should be fairly straightforward, unless there are some new requirements introduced by General Data Protection Regulation (GDPR) I don't know of.

**Comment by jhuesser** [comment]
I've implemented this feature in PR #37 but with telegram instead of mail. Regarding GDPR you need to secure the personal data. Also you need to have a privacy policy wich contains who you are, what data you collect and why. Here is some more information: https://ec.europa.eu/justice/smedataprotect/index_en.htm

**Comment by Pryx** [comment]
With GDPR you also need double opt in mailing list and also it needs to be possible to remove subscription easily :slightly_smiling_face: Some kind of privacy policy page should be added either way

**Comment by jhuesser** [comment]
Correct. Should be something like
1. sign up for mail alerts
2. mail with register link is sent
3. user clicks on the link
4. subscription is registred
5. mails can be sent

opt out could be a link in the profile page and/or a unsubscribe link in the email to remove yourself from the DB.

**Comment by thnilsen** [comment]
I believe all of the requirements listed by @jhuesser are handled by #71
