### ISSUE TITLE
Email Subscriptions

### ISSUE THREAD

**Issue by thnilsen** [server-status-project/server-status#65]
In the milestone list for v1.2 I see that Mailinglist is one of the items. I assume this is functionality to allow end users to get notified on status updates via email?

I would like to contribute to this function if possible. Are there any current work being done on this or do we start from scratch? Any thoughts or plans for how this should be implemented - both visually and functional wise? 

It might also be a good idea to add support for using PHPMailer or something similar in order to allow a more varied mail option and not just rely on the mail() function.

**Comment by Pryx** [comment]
You are certainly welcome to pick that issue up. In fact I am grateful for any contribution, as I am very busy lately. 

Using PHPMailer is a great idea and something I would really love to see. In fact as far as I remember Server status has text-only emails, which could be really improved upon with some email templates.

There is no current work, because I didn't really want to start before I knew more about the GDPR regulations. In fact Server status still isn't 100% GDPR compliant IMO (not really possible to export information or delete data unless you know SQL).

What I would like to see though is - dropdown menu for subscriptions at the top page (so it is possible to include #37 in there as well). In there there could be link to a page that would allow you to subscribe or unsubscribe, preferably with captcha. I am not really set on how it should look like though, but styling is the easy part 🙂

**Comment by thnilsen** [comment]
I have gotten some of the code for subscription up and running. I used the basis of #37 but modified the sql schema a bit to cater for different types of subscriptions. Will commit some code for review once I've got all the basic functions working. 

I have added support for reCaptcha during singup. This can be turned on/off from config.php

Subscription will generate a random 32 byte token that follows the user's life. This seems to be the way other similar systems does it as well, and it doesn't require any login/password validation code. The authkey is generated using openssl lib in php (will be another dependency).

```
$token = openssl_random_pseudo_bytes(32);  //Convert the binary data into hex  
$token = bin2hex($token); //Make it url friendly...
```

Here are some screenshots of current work...

**Subscription signup form**
![image](https://user-images.githubusercontent.com/10619272/48584437-fe0d1000-e929-11e8-8286-ff928d7034fe.png)

**Signup post screen**
![image](https://user-images.githubusercontent.com/10619272/48584493-26950a00-e92a-11e8-95b6-07a96dc76217.png)

**Unsubscribe verification screen**
![image](https://user-images.githubusercontent.com/10619272/48584573-665bf180-e92a-11e8-90a3-92a3463bca7d.png)

**Status update email**
![image](https://user-images.githubusercontent.com/10619272/48585822-28f96300-e92e-11e8-9502-985a2b8857fa.png)

**Comment by thnilsen** [comment]
Basic email subscription code is now working with signup, validating, unsubscribe, add and remove. Menus, email templates will need some design. you can take a look at the working example on https://server-status.ddns.doc-s.co.uk/.

It uses the same subscriber add/remove code as the proposed Telegram integration code.

**Comment by myhexa** [comment]
@thnilsen Very cool feature! Would be a good idea to create a pull request for that. That would be great to have! Also, does this feature use the PHP mail() function?

**Comment by thnilsen** [comment]
I will be creating a PR within the next few days. Just want to clean up the code a bit.
At the moment it is relying on the standard mail() function, but I do plan to adding support for PHPMailer as well.

**Comment by yigitkeremoktay** [comment]
This feature is implemented. Thanks @thnilsen
